name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 * * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          REPOSITORY: SideeID/SideeID
          SHOW_TITLE: true
          TIME_RANGE: all_time
          LANG_COUNT: 6
          SHOW_TIME: true
          SHOW_TOTAL: true
          # BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          BLOCKS: ▱▰
          STOP_AT_OTHER: true
          SHOW_MASKED_TIME: false
          CODE_LANG: javascript
          IGNORED_LANGUAGES: HTML, PHP
          
          
